### ISSUE TITLE
No file named face_recognition

### ISSUE THREAD

**Issue by SalahuddinX** [jomariya23156/face-recognition-with-liveness-web-login#1]
Hello! I cloned the repository, and encountered this error 
No module named face_recognition

I tried to find this file, but there was no such file

@jomariya23156

**Comment by jomariya23156** [comment]
It's a package. So, you can simply use `pip install face_recognition`
This is the [link](https://face-recognition.readthedocs.io/en/latest/index.html) to the doc.
