### ISSUE TITLE
show error

### ISSUE THREAD

**Issue by Suriya09876** [jomariya23156/face-recognition-with-liveness-web-login#2]
I can't install dlib==19.22.99 in python 3.9.5 is not supported showing error. can you give idea how to install and run the project?

**Comment by jomariya23156** [comment]
You can try a different version of dlib. I believe it would work the same.

**Comment by Suriya09876** [comment]
> You can try a different version of dlib. I believe it would work the same.

hi bro i want contact you, shall i contact in linkedin?

**Comment by Suriya09876** [comment]
when i try to run python file app.py is loading login page its only provide sign in how to sign up to enter credentials? and how to setup database.sqlite in pycharm bcz i used pycharm for this project pls tell me bro

**Comment by Suriya09876** [comment]
usage: encode_faces.py [-h] -i DATASET -e ENCODING [-d DETECTION_METHOD]
encode_faces.py: error: the following arguments are required: -i/--dataset, -e/--encoding

usage: recognize_faces.py [-h] -e ENCODINGS [-d DETECTION_METHOD]
recognize_faces.py: error: the following arguments are required: -e/--encodings

showing this kind of errors while try to run encode_faces.py and recognize_faces.py

**Comment by Suriya09876** [comment]
how long take time to recognize face while train our model?

**Comment by jomariya23156** [comment]
Here's my linkedin https://www.linkedin.com/in/ariya-sontrapornpol/ . Technically, there's no training for face recognition with this approach i used. There's instead training a model for liveness classification (fake/real) and the training time depends on how large your dataset is, but model itself is quite small.

**Comment by Prakash147** [comment]
Hiii sir, I have a doubt which technology you used in this project for recognizing liveness detection?

**Comment by jomariya23156** [comment]
> Hiii sir, I have a doubt which technology you used in this project for recognizing liveness detection?

It's a simple classification CNN model.
