### ISSUE TITLE
Reference paper for the project

### ISSUE THREAD

**Issue by qingshou0626** [jomariya23156/face-recognition-with-liveness-web-login#3]
I would like to read the reference paper for this project. Do you still keep the reference paper?

**Comment by jomariya23156** [comment]
Sure. Here is the list of papers and articles:
- https://arxiv.org/pdf/1405.2227.pdf (liveness detection)
- https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78 (face recognition)
- https://blog.dlib.net/2017/02/high-quality-face-recognition-with-deep.html (face recognition)

You can also check out 2 blogs from Pyimagesearch I put at the very end of README.
